apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumeMounts[0].name }}
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}