apiVersion: v1
kind: Service
metadata:
  name: {{ include "decisionsvc.fullname" . }}
  labels:
    {{- include "decisionsvc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.https }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "decisionsvc.selectorLabels" . | nindent 4 }}
