services:
  insurance-data-mgr:
    image: athenadecisionsystems/ibu-insurance-data-mgr:1.0.0
    hostname: datamgr
    container_name: datamgr
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=p0stgrespwd
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/insurancedb
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgrespwd
      - POSTGRES_DB=insurancedb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./data/claimdb:/var/lib/postgresql/data