apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: owl-frontend
  name: owl-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: owl-frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: owl-frontend
    spec:
      containers:
        - env:
            - name: REACT_APP_ASSISTANT_ID_WITHOUT_RULES
              value: '''ibu_assistant_limited'''
            - name: REACT_APP_ASSISTANT_ID_WITH_RULES
              value: '''ibu_assistant'''
            - name: REACT_APP_BACKEND_URL
              value: http://localhost:8000/api/v1/
            - name: REACT_APP_DEMO_TEXT
              value: '"My name is Sonya Smith, I have problem with my claim 2 for my water damage, my carpet is expensive, I m surprise of the current coverage, very disappointing?"'
            - name: REACT_APP_OWL_AGENT_NAME
              value: '"IBU Insurance Management Agent"'
          image: jbcodeforce/athena-owl-frontend:latest
          name: owl-frontend
          ports:
            - containerPort: 80
              protocol: TCP
      hostname: owl-frontend
      restartPolicy: Always
