hello_world_agent:
  name: Hello World Agent
  description: OpenAI based agent with simple prompt 
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-4o-2024-08-06
  prompt_ref: openai_functions_prompt
  temperature: 0
  top_k: 1
  top_p: 1


hello_world_agent_with_tools:
  name: Hello World Agent with Tools
  description: OpenAI based agent with simple prompt 
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-4o-2024-08-06
  prompt_ref: openai_functions_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
    - tavily
    - get_client_by_email_id