logging_level: DEBUG
version: v0.0.7_dev

owl_env_path: ../../.env
#app_index_path: /app/routers/index.html

owl_glossary_path: config/glossary.json
owl_agents_path: config/agents.yaml
owl_tools_path: config/tools.yaml
owl_prompts_path: config/prompts.yaml

owl_agent_content_file_path: ../../datastore/file_uploads

# do not use chroma in client server in cost use case
# owl_agent_vs_url: http://localhost:8010
owl_agent_vs_path: ../../datastore/vector_store_db

owl_agent_content_collection_name: base_collection

owl_agent_vs_class_name: langchain_chroma.Chroma
owl_agent_vs_embedding_fct: OpenAIEmbeddings
owl_agent_vs_embedding_fct_model: text-embedding-3-large
owl_agent_llm_history_length: 5
owl_agent_tool_factory_class:  ibu.llm.tools.client_tools.MyApplicationToolInstanceFactory
owl_agent_decision_service_fct_name: athena.itg.decisions.nba_ds_dummy.callDecisionService
owl_agent_default_agent: openai_chain_agent
watsonx_ai_url: https://us-south.ml.cloud.ibm.com
watsonx_ai_project_id: bddd370f-77c3-4b6e-a18b-3ef7f4ca1bae
watsonx_ai_model: "ibm/granite-13b-instruct-v2"
