ibu_agent:
  name: IBU Customer Support agent
  description:  OpenAI based agent with tools and trustable decisions
  runner_class_name: ibu.llm.agents.ibu_agent_lg3.IBUInsuranceAgent
  hidden_to_ui: false
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
    - ibu_client_by_id

ibu_classify_query_watson_agent:
  name: "Classify query Watson Llama 3 Agent"
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  description: A default agent that uses LLM using WatsonX and Llama3
  modelName: meta-llama/llama-3-3-70b-instruct
  modelClassName: langchain_ibm.WatsonxLLM
  prompt_ref: classify_query__llama_prompt
  temperature: 0
  hidden_to_ui: true
  top_k: 1
  top_p: 1

ibu_information_agent:
  name: OpenAI IBU agent with RAG Limited
  description: OpenAI IBU agent with RAG and insurance tools without decision service
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-4o-2024-11-20
  prompt_ref: ibu_rag_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  hidden_to_ui: true
  tools:
    - ibu_client_by_id
    - ibu_client_by_name
    - ibu_claim_by_id
    - ibu_claim_status_by_user_name
    - rag_insurance_corpus

extract_info_to_decide:
  name: Extract information need by the next best action decision service
  description: OpenAI agent to extract data from input query
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-4o-2024-11-20
  prompt_ref: extract_info_to_decide_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  hidden_to_ui: true
  tools:
    - ibu_client_by_id

ibu_complaint_agent:
  name: RAG with Decision Agent
  description: OpenAI IBU agent with RAG and insurance tools with decision service
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-4o-2024-11-20
  prompt_ref: openai_insurance_with_tool
  temperature: 0
  top_k: 1
  top_p: 1
  hidden_to_ui: true
  tools:
    - ibu_client_by_id
    - ibu_client_by_name
    - ibu_claim_by_id
    - ibu_claim_status_by_user_name
    - ibu_best_action
    - rag_insurance_corpus

ibu_complaint_agent2:
  name: RAG with no Decision Agent
  description: OpenAI IBU agent with RAG and insurance tools
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-4o-11-20
  prompt_ref: openai_insurance_with_tool
  temperature: 0
  top_k: 1
  top_p: 1
  hidden_to_ui: true
  tools:
    - ibu_client_by_id
    - ibu_client_by_name
    - ibu_claim_by_id
    - ibu_claim_status_by_user_name
    - rag_insurance_corpus
