ibu_agent:
  agent_id: ibu_agent
  name: ibu_agent
  description:  OpenAI based agent with tools to support the IBU insurance demo and variable model 
  runner_class_name: ibu.llm.agents.ibu_agent_lg.IBUInsuranceAgent
  hidden_to_ui: false
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
    - ibu_client_by_id
    - ibu_client_by_name
    - ibu_claim_by_id
    - ibu_claim_status_by_user_name
    - ibu_best_action
    - tavily
    - rag_insurance_corpus


watson_llama_3_70_agent:
  agent_id: watson_llama_3_70_agent
  name: "WatsonX.ai Llam 3 70b Instruct Agent"
  description: WatsonX ai with Llama 3 at 70b parameters
  runner_class_name: athena.llm.agents.adaptive_rag_graph.SequenceOfActionAgent
  modelName: meta-llama/llama-3-70b-instruct
  modelClassName: langchain_ibm.WatsonxLLM
  prompt_ref: llama_base_prompt
  temperature: 0
  top_k: 20
  top_p: 1

ibu_classify_query_agent:
  agent_id: ibu_classify_query_agent
  name: IBU Classify Query Agent
  description: OpenAI Agent to classify a query as Information or Complaint
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-4o-2024-08-06
  prompt_ref: classify_query_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  hidden_to_ui: true

ibu_information_agent:
  agent_id: ibu_information_agent
  name: OpenAI IBU agent with RAG Limited
  description: OpenAI IBU agent with RAG and insurance tools without decision service
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-4o-2024-08-06
  prompt_ref: ibu_rag_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  hidden_to_ui: true
  tools:
    - ibu_client_by_id
    - ibu_client_by_name
    - ibu_claim_by_id
    - ibu_claim_status_by_user_name
    - tavily
    - rag_insurance_corpus


ibu_complaint_agent:
  agent_id: ibu_complaint_agent
  name: RAG with Decision Agent
  description: OpenAI IBU agent with RAG and insurance tools with decision service
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-4o-2024-08-06
  prompt_ref: openai_insurance_with_tool
  temperature: 0
  top_k: 1
  top_p: 1
  hidden_to_ui: true
  tools:
    - ibu_client_by_id
    - ibu_client_by_name
    - ibu_claim_by_id
    - ibu_claim_status_by_user_name
    - ibu_best_action
    - rag_insurance_corpus

