ibu_agent:
  agent_id: ibu_agent
  name: ibu_agent
  description:  OpenAI based agent with tool to support the IBU insurance demo and variable model 
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelName: gpt-4o-2024-08-06
  modelClassName: langchain_openai.ChatOpenAI
  prompt_ref: openai_insurance_with_tool
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
    - ibu_client_by_id
    - ibu_client_by_name
    - ibu_claim_by_id
    - ibu_claim_status_by_user_name
    - ibu_best_action

ibu_agent_limited:
  agent_id: ibu_agent_limited
  name: ibu_agent
  description: OpenAI based agent with tool IBU loan app prompt without decision service
  runner_class_name: ibu.llm.agents.ibu_agent_lg.IBUInsuranceAgent
  prompt_ref: openai_insurance_with_tool
  # hwchase17/react-chat-json 

ibu_classify_query_agent:
  agent_id: ibu_classify_query_agent
  name: IBU Classify Query Agent
  description: OpenAI Agent to classify a query as Information or Complaint
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-4o-2024-08-06
  prompt_ref: classify_query_prompt
  temperature: 0
  top_k: 1
  top_p: 1

ibu_tool_rag_agent_limited:
  agent_id: ibu_tool_rag_agent_limited
  name: OpenAI IBU agent with RAG Limited
  description: OpenAI IBU agent with RAG and insurance tools without decision service
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-4o-2024-08-06
  prompt_ref: ibu_rag_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
    - ibu_client_by_id
    - ibu_client_by_name
    - ibu_claim_by_id
    - ibu_claim_status_by_user_name
    - tavily

ibu_tool_rag_ds_agent:
  agent_id: ibu_tool_rag_ds_agent
  name: RAG with Decision Agent
  description: OpenAI IBU agent with RAG and insurance tools with decision service
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-4o-2024-08-06
  prompt_ref: ibu_rag_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
    - ibu_best_action
    - ibu_client_by_id
    - ibu_client_by_name
    - ibu_claim_status_by_user_name
    - ibu_claim_by_id
