logging_level: DEBUG
version: v0.0.7_dev

owl_env_path: ../../.env
#app_index_path: /app/routers/index.html

owl_glossary_path: config/glossary.json
owl_agents_path: config/agents.yaml
llm_providers_path: config/llm_providers.yaml
owl_tools_path: config/tools.yaml
owl_prompts_path: config/prompts.yaml
owl_prompts_key_name: openai_insurance_with_tool

owl_agent_content_collection_name: ibu_insurance
owl_agent_content_file_path: ../../datastore/file_uploads

# do not use chroma in client server in cost use case
# owl_agent_vs_url: http://localhost:8010
owl_agent_vs_path: ../../datastore/vector_store_db
owl_agent_vs_class_name: langchain_chroma.Chroma
owl_agent_vs_embedding_fct: OpenAIEmbeddings
owl_agent_vs_embedding_fct_model: text-embedding-3-large
owl_agent_llm_history_length: 5
owl_agent_tool_factory_class:  ibu.llm.tools.client_tools.IbuInsuranceToolInstanceFactory
owl_best_action_ds_url: http://localhost:9060/DecisionService/rest/v1/ComplaintHandling/1.0/nextBestAction/
owl_agent_default_agent: openai_chain_agent

app_insurance_client_repository: ibu.itg.ds.insurance_client_repo_filesystem.InsuranceClientFromFileSystem
app_insurance_claim_repository: ibu.itg.ds.insurance_claim_repo_filesystem.InsuranceClaimFromFileSystem
app_insurance_data_folder: ../../datastore/insuranceclaims-data
#app_insurance_client_repository: ibu.itg.ds.insurance_client_repo_datamgr.InsuranceClientFromDataMgr
#app_insurance_claim_repository: ibu.itg.ds.insurance_claim_repo_datamgr.InsuranceClaimFromDataMgr
#app_insurance_backend_url: http://localhost:8080/repository

watsonx_ai_url: https://eu-de.ml.cloud.ibm.com
watsonx_ai_project_id: baa31d24-8eba-4765-af2a-4a3d9d364554
watsonx_ai_model: "ibm/granite-13b-instruct-v2"