tavily:
  tool_class_name: TavilySearchResults
  tool_description: 'A search engine optimized for comprehensive, accurate, and trusted results about recent events, like weather'
  tool_fct_name: TavilySearchResults
  tool_name: "tavily search"
  tags:
    - websearch


ibu_client_by_id:
  tool_name: "Client by ID"
  tool_class_name: 'ibu.llm.tools.client_tools'
  tool_description: 'get insurance customer information given a unique client identifier id'
  tool_fct_name: get_client_by_id
  tags:
    - internal_tool

ibu_client_by_name:
  tool_name: "Client by lastname and firstname"
  tool_class_name: 'ibu.llm.tools.client_tools'
  tool_description: 'get customer details given their last name and first name'
  tool_fct_name: get_client_by_name
  tags:
    - internal_tool

ibu_claim_by_id:
  tool_name: "claim by id or number"
  tool_class_name: 'ibu.llm.tools.client_tools'
  tool_description: 'get insurance claim details given a unique claim identifier id or number'
  tool_fct_name: get_claim_by_id
  tags:
    - internal_tool


ibu_best_action:
  tool_name: "Best action for claim processing"
  tool_class_name: ibu.llm.tools.client_tools
  tool_description: |
    This is an IBM ODM business rules decision service that provides action recommendation based on the company's policies.
    You provide the customer's motivation, intention to change to a competitor, and the claim id. The tool provides actions to be taken and which business rule was used to make a decision.
  tool_fct_name: define_next_best_action_with_decision
  tags:
    - internal_tool
    - decision

ibu_claim_status_by_user_name:
  tool_name: "Claim status for a give client name"
  tool_class_name: ibu.llm.tools.client_tools
  tool_description: |
    "Finds the current insurance claim status of an client given their last name and first name."
  tool_fct_name: get_claim_status_by_user_name  
  tags:
    - internal_tool

rag_insurance_corpus:
  tool_name: "Use RAG on IBU corpus"
  tool_description: |
    "when asked for information about insurance policies, use this tool to get tailored content from uploaded documents"
  tool_class_name: ibu.llm.tools.client_tools
  tool_fct_name: search_corpus
  tags:
    - internal_tool
    - rag