tavily:
  tool_id: tavily
  tool_class_name: TavilySearchResults
  tool_description: 'A search engine optimized for comprehensive, accurate, and trusted results about recent events, like weather'
  tool_fct_name: TavilySearchResults
  tool_name: "tavily search"
  tags:
    - websearch


ibu_client_by_id:
  tool_id: ibu_client_by_id
  tool_name: "Client by ID"
  tool_class_name: 'ibu.llm.tools.client_tools'
  tool_description: 'get insurance client information given its unique client identifier id'
  tool_fct_name: get_client_by_id
  tags:
    - internal_tool

ibu_client_by_name:
  tool_id: ibu_client_by_name
  tool_name: "Client by lastname and firstname"
  tool_class_name: 'ibu.llm.tools.client_tools'
  tool_description: 'get client information given his or her lastname and firstname'
  tool_fct_name: get_client_by_name
  tags:
    - internal_tool

ibu_claim_by_id:
  tool_id: ibu_claim_by_id
  tool_name: "claim by id"
  tool_class_name: 'ibu.llm.tools.client_tools'
  tool_description: 'get insurance claim information given its unique claim identifier id'
  tool_fct_name: get_claim_by_id
  tags:
    - internal_tool


ibu_best_action:
  tool_id: ibu_best_action
  tool_name: "Best action for claim processing"
  tool_class_name: ibu.llm.tools.client_tools
  tool_description: |
    "perform the next best action given the current state of the insurance claim 
    knowing its unique claim_id and the current client's motivation.
    Extract the client motive and whether he has the intention to churn"
  tool_fct_name: define_next_best_action_with_decision
  tags:
    - internal_tool
    - decision

ibu_claim_status_by_user_name:
  tool_name: "Claim status for a give client name"
  tool_id: ibu_claim_status_by_user_name
  tool_class_name: ibu.llm.tools.client_tools
  tool_description: |
    "get the last status for the claim of an insured person giving her/his lastname and firstname."
  tool_fct_name: get_claim_status_by_user_name  
  tags:
    - internal_tool