# generated by datamodel-codegen:
#   filename:  MydeploymentMiniloan_ServiceRulesetDecisionService.yaml
#   timestamp: 2024-06-26T05:37:16+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Borrower(BaseModel):
    name: Optional[str] = None
    creditScore: Optional[int] = None
    yearlyIncome: Optional[int] = None


class Loan(BaseModel):
    amount: Optional[int] = None
    duration: Optional[int] = None
    yearlyInterestRate: Optional[float] = None
    yearlyRepayment: Optional[int] = None
    approved: Optional[bool] = False
    messages: Optional[List[str]] = []


class Error(BaseModel):
    code: Optional[int] = Field(None, description='HTTP error code.')
    message: Optional[str] = Field(None, description='Error message.')
    details: Optional[str] = Field(None, description='Detailed error message.')
    errorCode: Optional[str] = Field(None, description='Product error code.')


class Request(BaseModel):
    field__DecisionID__: Optional[str] = Field(
        None,
        alias='__DecisionID__',
        description='Unique identifier representing the execution of the decision service operation. If it is not specified, it will be computed automatically.',
    )
    borrower: Optional[Borrower] = None
    loan: Optional[Loan] = None


class Response(BaseModel):
    field__DecisionID__: Optional[str] = Field(
        None,
        alias='__DecisionID__',
        description='Unique identifier representing the execution of the decision service operation. If it is not specified, it will be computed automatically.',
    )
    loan: Optional[Loan] = None
