# Copyright 2024 Athena Decision Systems
# @author Jerome Boyer
# IBU Loan Application Demo
# ------------------------------------------------------------------
ibu_agent:
  agent_id: ibu_agent
  name: IBU Loan Agent with Decision Engine
  description: OpenAI based agent with IBU loan app prompt and tools
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelName: gpt-4o
  modelClassName: langchain_openai.ChatOpenAI
  prompt_ref: ibu_loan_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - ibu_client_by_name
  - ibu_loan_assessment_action

ibu_agent_limited:
  agent_id: ibu_agent_limited
  name: IBU Loan Agent without Decision
  description: OpenAI based agent with IBU loan app prompt without decision service
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentDefaultRunner
  modelName: gpt-4o
  modelClassName: langchain_openai.ChatOpenAI
  prompt_ref: ibu_loan_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - ibu_client_by_name
