# Copyright 2024 Athena Decision Systems
# @author Jerome Boyer
# IBU Loan Application Demo
# ------------------------------------------------------------------
openai_chain_tool:
  agent_id: openai_chain_tool
  name: open_ai_gpt35
  description: openai based agent with prompt coming from langchain hub  and tool
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentAbstractRunner
  modelName: gpt-3.5-turbo
  modelClassName: langchain_openai.ChatOpenAI
  prompt_ref: openai_functions_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - tavily


ibu_agent:
  agent_id: ibu_agent
  name: ibu_agent
  description: openai based agent with IBU loan app prompt and tools
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentAbstractRunner
  modelName: gpt-3.5-turbo
  modelClassName: langchain_openai.ChatOpenAI
  prompt_ref: ibu_loan_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - ibu_client_by_name
  - ibu_loan_assessment_action

ibu_agent_limited:
  agent_id: ibu_agent_limited
  name: ibu_agent_limited
  description: openai based agent with IBU loan app prompt without decision service
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentAbstractRunner
  modelName: gpt-3.5-turbo
  modelClassName: langchain_openai.ChatOpenAI
  prompt_ref: ibu_loan_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - ibu_client_by_name
