services:
  owl-backend:
    hostname: owl-backend
    image: athenadecisionsystems/athena-owl-backend:1.0.0
    pull_policy: always
    container_name: owl-backend
    ports:
      - 8000:8000
    environment:
      - CONFIG_FILE=/app/config/config.yaml
      - PYTHONPATH=/app/ibu
    env_file:
      - ../../.env
    volumes:
      - ../../ibu_backend/src/config:/app/config
      - ../../.env:/app/.env
      - ./data/file_content:/app/file_content
      - ./data/vs_db:/app/vs_db
      - ../../ibu_backend/src/ibu:/app/ibu
  owl-frontend:
    hostname: owl-frontend
    image: athenadecisionsystems/athena-owl-frontend:1.0.0
    pull_policy: always
    container_name: owl-frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_OWL_AGENT_NAME="MiniLoan Management Agent"
      - NEXT_PUBLIC_BACKEND_BASE_API=http://localhost:8000/api/v1/
      - REACT_APP_AGENT_ID_WITH_RULES='ibu_agent'
      - REACT_APP_AGENT_ID_WITHOUT_RULES='ibu_agent_limited'
      - REACT_APP_DEMO_TEXT="One of our client Robert Smith wants a loan for \$500,000 for a duration of 60 months and a yearly repayment of $60,000 do we approve it?"

  decisionsvc:
    image: icr.io/cpopen/odm-k8s/odm:8.12
    hostname: decisionsvc
    container_name: decisionsvc
    ports:
      - 9443:9443
      - 9060:9060
    user: "1001:0"
    environment:
      - SAMPLE=false
      - LICENSE=accept
    volumes:
      - ./data/res:/config/dbdata
