services:
  owl-backend:
    hostname: owl-backend
    image: athenadecisionsystems/athena-owl-backend:1.0.0
    container_name: owl-backend
    ports:
      - 8000:8000
    environment:
      CONFIG_FILE: /app/config/config.yaml
      OPENAI_API_KEY: $OPENAI_API_KEY
    volumes:
      - ../../ibu_backend/src/config:/app/config
      - ../../.env:/app/.env
      - ./data/file_content:/app/file_content
      - ./data/chromadb:/app/chromadb
      - ../../ibu_backend/src/ibu:/app/ibu
  insurance-data-mgr:
    image: athenadecisionsystems/ibu-insurance-data-mgr:1.0.0 
    hostname: datamgr
    container_name: datamgr
    depends_on:
      - postgres
    ports: 
      - 8080:8080
    environment:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=p0stgrespwd
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/insurancedb
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgrespwd
      - POSTGRES_DB=insurancedb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - ./data/claimdb:/var/lib/postgresql/data
  decisionsvc:
    image: icr.io/cpopen/odm-k8s/odm:8.12
    hostname: decisionsvc
    container_name: decisionsvc
    ports:
      - 9443:9443
      - 9060:9060
    environment:
      - SAMPLE=false
      - LICENSE=accept
    volumes:
      - ../../decisions/persistence:/config/dbdata/
  chroma-db:
    image: ghcr.io/chroma-core/chroma:latest
    hostname: chroma-db
    container_name: chroma-db
    volumes:
      - ./chromadb:/.chroma/index
    ports:
      - 8005:8000
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgagmin
    container_name: pgadmin
    restart: always
    profiles: 
      - dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - "5050:80"
    volumes: 
      - ./data_files:/tmp/data_files