name: Build and Publish image to docker
on:
  push:
    branches:
      - main
      
    paths-ignore:
      - 'docs/**'
      - '.vscode/**'
      - 'deployment/**'
      - 'tools/**'
      - 'owl-agent-frontend/**'
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4
      - name: Check out owl core repo
        uses: actions/checkout@v4
        with: 
          repository: https://github.com/AthenaDecisionSystems/athena-owl-core
          ref: refs/heads/development
          path: owl_core
      - name: build ibu ins data access image
        run: |
          docker login -u ${{ env.DOCKER_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker build IBU-insurance-demo/datamgt/code/apis-datamgr-insurance-pc-claims/ -t athenadecisionsystems/ibu-insurance-data-mgr:1.0.0 

      
      
